- tests/e2e/docker/Dockerfile
This fix detects packaging issues with e2e tests (see #254)
> fix e2e test package import

- Earthfile
- jest.config.js
- stryker.conf.js
- tests/integration/lib/generator.spec.js
- tests/unit/lib/diff.test.js
- tests/unit/lib/graphql.test.js
- tests/unit/lib/printer.test.js
- tests/unit/lib/renderer.test.js
- tests/unit/lib/utils.test.js
Solve local execution issues
Improve execution time
> Update stryker config

- CONTRIBUTING.md
> add first version of contributing guide

- Earthfile
- README.md
- package.json
> GraphQL package as peer dependency

- dangerfile.js
- package.json
- src/lib/generator.js
- yarn.lock
> remove picocolors dependency

- src/index.js
Hey @edno, Thanks for this package! 
I've noticed that the groupBy config was not applied correctly if you don't use the command line option and found this small oversight.
Thanks ahead for your help!
> Fix: apply groupByDirective option from config file

- src/config.js
- src/utils/scalars/string.js
- tests/integration/lib/generator.spec.js
- tests/unit/config.test.js
- tests/unit/utils/scalars/array.test.js
- tests/unit/utils/scalars/string.test.js
> test: improve coverage

- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
> add pr template

- src/lib/diff.js
- src/lib/printer.js
- src/lib/renderer.js
- tests/e2e/specs/cli.spec.js
- tests/unit/lib/diff.test.js
- tests/unit/lib/printer.test.js
- tests/unit/utils/scalars/object.test.js
> :bug: fix sonar issues

- sonar-project.properties
add sonarcloud config for keys that cannot be set in UI.
> :wrench:  add sonar properties file

- package.json
> :wrench:  prepare release 1.9.2

- .docs/custom.css
- .npmignore
- Earthfile
- scripts/config-plugin.js
> :memo: update doc css

- .github/workflows/publish-docs.yaml
- Earthfile
> 👷  fix publish-docs job

- .github/workflows/danger-js.yml
- .github/workflows/linter.yml
- .github/workflows/mutation.yml
- .github/workflows/smoke.yml
- .github/workflows/test.yml
- .gitignore
- .vscode/extensions.json
Housekeeping task to keep things up to date for devx.
>  🧑‍💻 devx housekeeping

- package.json
- yarn.lock
update dev dependencies to latest revision.
> :package:  update dev dependencies

- package.json
- yarn.lock
update dependencies to latest revision
> :package:  update dependencies

- .earthignore
- .vscode/settings.json
- Earthfile
Refactor earthfile to align with Earthly recommended practices.
> :wrench:  update earthfile

- .docs/custom.css
Use Infima variables for fonts (best practice).
> :memo:  use infima variables for fonts

- Earthfile
- README.md
- src/config.js
- src/index.js
- src/lib/generator.js
- src/lib/printer.js
- src/lib/renderer.js
- tests/__data__/anilist.md
- tests/__data__/docusaurus2-graphql-doc-generator-groups.config.js
- tests/e2e/jest.config.js
- tests/integration/jest.config.js
- tests/integration/lib/__expect__/unix/generator.spec.js/generateDocFromSchemaOutputFolder.hash
- tests/integration/lib/__expect__/unix/generator.spec.js/generateDocFromSchemaWithGroupingOutputFolder
- tests/unit/config.test.js
- tests/unit/jest.config.js
- tests/unit/lib/__expect__/unix/printer.test.js/printHeaderNoPagination.md
- tests/unit/lib/__expect__/unix/printer.test.js/printHeaderNoToC.md
- tests/unit/lib/__expect__/unix/printer.test.js/printTypeWithScalarWithSpecifiedBy.md
- tests/unit/lib/printer.test.js
> :sparkles: add doc options support

- src/lib/graphql.js
- tests/__data__/schema_with_grouping.graphql
- tests/integration/lib/__expect__/unix/generator.spec.js/generateDocFromSchemaWithGroupingOutputFolder
- tests/unit/lib/graphql.test.js
Fixes #543  printing of code snippet with default value of list enum.
> :bug:  fix rendering default array enum

- src/lib/renderer.js
- src/utils/helpers/fs.js
- tests/unit/lib/graphql.test.js
- tests/unit/lib/group-info.test.js
- tests/unit/lib/printer.test.js
- tests/unit/lib/renderer.test.js
- tests/unit/utils/scalars/string.test.js
Add unit tests to improve code coverage, with some refactoring of existing ones.
> 🧪 improve code coverage

- Earthfile
- stryker.conf.js
> 🧪 update StrykerJS config

- .github/workflows/publish-docs.yaml
> :construction_worker:  trigger doc generation on release

- package.json
- yarn.lock
> 🔖 release 1.11.0

- .github/dependabot.yml
Add Github Action to dependabot config.
> :wrench: update dependabot.yml

- .npmignore
- .prettierrc
- package.json
- tests/__data__/groups.md
- yarn.lock
Prepare release 1.12.0
✨ New features to make the documentation easier to navigate, based on a request from @LunaticMuch.
1. **Type relations** give you information about where a type is used: operation, union, interface, type... 
2. **Parent prefix** makes it easier to read fields in type pages, especially for nested ones
3. **Type attributes badges** provide a quick overview of the field attributes such as root type, list, nullability, and groups (if you use the [grouping feature](https://graphql-markdown.github.io/#option-groupbydirective))
👀  Look at [Demo 1](https://graphql-markdown.github.io/schema) to see how the documentation renders with those options.
ℹ️  All those options are enabled by default, but they can be toggled off if you don't need them, see the …
> release 1.12.0

- .github/workflows/mutation.yml
- .github/workflows/smoke.yml
- .github/workflows/test.yml
Avoid running tests when updating website files
> :construction_worker:  exclude website from github test actions

- Earthfile
- README.md
- docs/advanced/additional-schema.md
- docs/advanced/custom-root-types.md
- docs/advanced/group-by-directive.md
- docs/advanced/schema-loading.md
- docs/configuration.md
- docs/get-started.md
- docs/intro.md
- docs/settings.md
- package-lock.json
- package.json
- scripts/config-plugin.js
- src/config.js
- tests/unit/config.test.js
Rename package and bump version
> :bookmark:  rename package

- .github/workflows/mutation.yml
- config/index.js
- config/jest.config.js
- config/stryker.conf.js
- packages/core/stryker.conf.js
- packages/diff/stryker.conf.js
- packages/docusaurus/stryker.conf.js
- packages/printer-legacy/stryker.conf.js
- packages/utils/stryker.conf.js
> :construction_worker:  fix mutation testing job

- packages/printer-legacy/src/index.js
- packages/printer-legacy/tests/unit/__snapshots__/printer.test.js.snap
- packages/printer-legacy/tests/unit/printer.test.js
> ✨ add directive locations

- .github/workflows/mutation.yml
Now that mutation tests run quickly (2-3 minutes), they can be run on PRs.
>  👷 add mutation tests on PRs

- package-lock.json
- packages/core/package.json
- packages/diff/package.json
- packages/docusaurus/package.json
- packages/printer-legacy/package.json
- packages/utils/package.json
- packages/utils/tests/unit/graphql.test.js
> Release 1.16

- package-lock.json
- packages/core/package.json
- packages/core/src/generator.js
- packages/core/src/group-info.js
- packages/docusaurus/package.json
- packages/printer-legacy/package.json
Fix destructure property bug on core introduce on version 1.1.0
> :bug:  fix destructure property bug on core

- .github/workflows/linter.yml
- .husky/pre-commit
- package.json
- scripts/dep-checks.js
> :construction_worker:  add custom workspace dep checker

- website/package-lock.json
- website/package.json
- website/src/components/HomepageFeatures/index.js
- website/src/components/HomepageFeatures/styles.module.css
- website/src/pages/index.js
- website/src/pages/index.module.css
Fix issues when displaying website front page on mobile
> fix reactive css for website

- package-lock.json
- packages/core/package.json
- packages/diff/package.json
- packages/docusaurus/package.json
- packages/printer-legacy/package.json
- packages/utils/package.json
Maintenance release 1.16.2 (dependencies)
> release 1.16.2

- .github/workflows/mutation.yml
> remove mutation job concurrency limit

- Earthfile
- package-lock.json
- package.json
- packages/core/package.json
- packages/diff/package.json
- packages/docusaurus/package.json
- packages/printer-legacy/package.json
- packages/utils/package.json
> Release 1.16.3

- package-lock.json
- packages/core/package.json
- packages/diff/package.json
- packages/docusaurus/package.json
- packages/printer-legacy/package.json
- packages/utils/package.json
Release 1.16.4
---
🤩  @carolstran fixed a long due [DOM warning](https://github.com/graphql-markdown/graphql-markdown/issues/764) where `class` was used instead of `className` in React MDX component.
* 📦 update dependency @graphql-markdown/core to 1.1.4
* 📦 update dependency @graphql-markdown/printer-legacy to 1.1.4
* 📦 update dependency @graphql-markdown/utils to 1.1.3
* 📦 update peerDependency @graphql-markdown/diff to 1.0.5
* 📦 update peerDependency @graphql-markdown/printer-legacy to 1.1.4
* https://github.com/graphql-markdown/graphql-markdown/pull/765 by @carolstran
* 📦 update dependency @graphql-markdown/utils to 1.1.3
* 📦 update dependency @graphql-tools/load to 7.8.11
* 📦 update dependency @graphql-markdown/utils to 1.1.3
* 📦 update dependency @graphql-inspector/core to 3.5.0
* 📦 …
> Release 1.16.4

- package-lock.json
- website/package.json
> 📝 bump @docusaurus/core to 2.3.1

- docs/advanced/custom-root-types.md
- docs/advanced/group-by-directive.md
- docs/settings.md
> 📝  minor update docs

- packages/utils/src/graphql.js
- packages/utils/tests/__data__/schema_802.graphql
- packages/utils/tests/unit/__snapshots__/graphql.test.js.snap
- packages/utils/tests/unit/graphql.test.js
> :bug:  fix undefined on undeclared root type instead of empty object

- package-lock.json
- packages/core/package.json
- packages/diff/package.json
- packages/docusaurus/package.json
- packages/printer-legacy/package.json
- packages/utils/package.json
---
:bug:  fix undefined on undeclared root type instead of empty object reported by @LunaticMuch in https://github.com/graphql-markdown/graphql-markdown/issues/802
❕ _This release has some significant code refactoring. If you experience regressions with this release, [please report them](https://github.com/graphql-markdown/graphql-markdown/issues/new?assignees=edno&labels=bug&template=bug_report.md&title=)._
* 📦 npm(deps): Bump @graphql-tools/load from 7.8.11 to 7.8.12 by @dependabot in https://github.com/graphql-markdown/graphql-markdown/pull/781
* fix(deps): update dependency @graphql-inspector/core to v4 by @renovate in https://github.com/graphql-markdown/graphql-markdown/pull/783
* 📦 npm(deps): Bump @graphql-tools/load from 7.8.12 to 7.8.13 by @dependabot in …
> 🔖 release 1.16.7

- packages/docusaurus/tests/__data__/schema_with_grouping.graphql
- packages/printer-legacy/src/section.js
- packages/printer-legacy/tests/unit/section.test.js
Fix formatting of multiline description as in #808
> :bug:  fix multiline description formatting

- Earthfile
Refactor Earthfile to make it more readable.
> :construction_worker:  refactor earthfile

- docs/advanced/custom-directive.md
- packages/docusaurus/tests/__data__/anilist.md
- packages/docusaurus/tests/__data__/docusaurus2-graphql-doc-generator-groups.config.js
- packages/docusaurus/tests/__data__/groups.md
Update demo doc:
- keep config in demo homepage align with doc settings
- simplify `customDirective` example for group-by demo
> :memo:  update demo docs

- CONTRIBUTING.md
> :memo:  add mutation testing section to contrib doc

- website/docusaurus.config.js
> :memo:  add edit this page link to doc

- docs/advanced/custom-directive.md
- docs/advanced/group-by-directive.md
> :memo:  update doc for categories and directives

- package-lock.json
- packages/core/package.json
- packages/diff/package.json
- packages/docusaurus/package.json
- packages/printer-legacy/package.json
- packages/utils/package.json
:sparkle:  Add wildcard support for **`customDirective`**, more details in the [documentation](https://graphql-markdown.github.io/docs/advanced/custom-directive).
* :package: bump dependency @graphql-markdown/core from 1.4.1 to 1.4.2
* :package: bump dependency @graphql-markdown/printer-legacy from 1.3.1 to 1.3.2
* :package: bump dependency @graphql-markdown/utils from 1.4.0 to 1.4.1
* :package: bump peerDependency @graphql-markdown/printer-legacy from 1.3.1 to 1.3.2
* :package: bump peerDependency @graphql-markdown/@ from 1.0.10 to 1.0.11
* :package: bump dependency @graphql-markdown/utils from 1.4.0 to 1.4.1
* :package: fix(deps): update graphql-tools monorepo to v8 (major) by @renovate in https://github.com/graphql-markdown/graphql-markdown/pull/854
* :package: bump dependency …
> :bookmark:  release 1.18.2

- package-lock.json
- packages/docusaurus/package.json
- packages/docusaurus/src/index.js
Force loading  `@docusaurus/logger` when loading `@graphql-markdown/docusaurus`.
> :technologist:  force loading  @docusaurus/logger on module init

- website/package-lock.json
- website/package.json
Bump website dependency @cmfcmf/docusaurus-search-local to 1.1.0
> :package:  bump website dependency @cmfcmf/docusaurus-search-local

- package-lock.json
- packages/core/package.json
- packages/docusaurus/package.json
Technical release before migration to TS.
> :bookmark:  release 1.20.4

- config/.eslintrc.js
- packages/core/src/config.ts
- packages/core/src/diff.ts
- packages/core/src/graphql-config.ts
- packages/core/src/printer.ts
- packages/core/src/renderer.ts
- packages/printer-legacy/src/badge.ts
- packages/printer-legacy/src/graphql/directive.ts
- packages/printer-legacy/src/link.ts
- packages/printer-legacy/src/printer.ts
- packages/utils/src/graphql.ts
- packages/utils/src/object.ts
- packages/utils/src/string.ts
- packages/utils/tests/unit/group.test.ts
Enable eslint rule `"@typescript-eslint/no-unnecessary-condition": "error"`
> :wrench:  add eslint rule no-unnecessary-condition

- packages/printer-legacy/src/group.ts
- packages/printer-legacy/tests/unit/group.test.ts
- packages/printer-legacy/tests/unit/relation.test.ts
- packages/utils/src/string.ts
- packages/utils/tests/unit/string.test.ts
Refactor printer-legacy based on mutation test report
> :recycle: refactor printer legacy

- .github/workflows/mutation.yml
- .github/workflows/smoke.yml
- .github/workflows/test.yml
- Earthfile
- config/stryker.conf.js
- package.json
- packages/core/tsconfig.json
- packages/types/tsconfig.test.json
Update jest and stryker config for CI speed improvement:
- dedicated test command `test:ci` for CI
- enable concurrency on long workflows: mutation and smoke tests
- disable long workflows from draft pr: mutation and smoke tests
- trigger tong workflows when PR ready for review: mutation and smoke tests
> :construction_worker:  optimize ci workflows

- .github/workflows/test.yml
- .vscode/settings.json
- package.json
- packages/printer-legacy/src/badge.ts
- packages/printer-legacy/tests/unit/badge.test.ts
- packages/printer-legacy/tests/unit/printer.test.ts
- packages/printer-legacy/tests/unit/relation.test.ts
Fix tests that failed when running jest with `--random`.
> :test_tube: fix tests failing on random sequence

- packages/types/LICENSE
- packages/types/README.md
Add missing LICENSE and README.md for types package
> :memo:  add missing LICENSE and README.md for types package

- docs/advanced/schema-loading.md
Update schema loader documentation with a example of module option based on comment from @JamieS1211 in #815.
> 📝 update schema loader documentation

- .github/workflows/publish-docs.yaml
- Earthfile
- docs/settings.md
- packages/utils/src/array.ts
- typedoc.base.json
- website/docusaurus.config.js
- website/package-lock.json
- website/package.json
> 📝upgrade website to docusaurus v3

- .github/workflows/smoke.yml
- packages/printer-legacy/src/common.ts
- packages/printer-legacy/tests/unit/common.test.ts
> add docusaurus v3 support

- website/docusaurus.config.js
- website/src/css/custom.css
Update announcement bar for compatibility with Docusaurus v3
> :memo:  update announcement bar for compatibility with Docusaurus v3

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
> :technologist:  update devcontainer config

- package-lock.json
- packages/printer-legacy/package.json
- packages/printer-legacy/src/common.ts
- packages/printer-legacy/tests/unit/common.test.ts
- packages/printer-legacy/tests/unit/graphql/directive.test.ts
- packages/printer-legacy/tests/unit/graphql/enum.test.ts
- packages/printer-legacy/tests/unit/graphql/object.test.ts
- packages/printer-legacy/tests/unit/graphql/operation.test.ts
- packages/printer-legacy/tests/unit/section.test.ts
> :sparkles:  (feat) replace caution admonition by warning for docusaurus v3

- scripts/docs-api.sh
Fix broken API docs generation.
> :construction_worker:  fix api doc generation

- package-lock.json
- packages/core/package.json
- packages/docusaurus/package.json
- packages/printer-legacy/package.json
Fix release 1.21.2 build issue
> 🔖 release 1.21.2

- website/package-lock.json
- website/package.json
Update website dependencies including fix for https://security.snyk.io/vuln/SNYK-JS-SERIALIZEJAVASCRIPT-6147607
> :package:  update website dependencies

- packages/printer-legacy/src/relation.ts
- packages/printer-legacy/tests/unit/relation.test.ts
Fix tests for module `printer-legacy/relation` based on Stryker report.
> :test_tube:  fix printer-legacy relations tests

- Earthfile
> :construction_worker:  upgrade earthly to 0.8

- docs/advanced/examples.md
- package-lock.json
- packages/core/tests/unit/diff.test.ts
- packages/diff/tests/unit/diff.test.ts
- packages/docusaurus/tests/__data__/schema_with_grouping.graphql
- packages/graphql/src/guard.ts
- packages/graphql/src/introspection.ts
- packages/graphql/tests/unit/introspection.test.ts
- packages/helpers/tests/unit/directives/descriptor.test.ts
- packages/printer-legacy/src/example.ts
- packages/printer-legacy/tests/unit/example.test.ts
- packages/types/package.json
- packages/types/src/core.d.ts
- packages/types/src/index.d.ts
Last PR for the first implementation of examples using directive (#1292). This PR adds support for operations.
> ✨ (feat) support examples operations

- .devcontainer/Dockerfile
- .devcontainer/base.Dockerfile
- .devcontainer/devcontainer.json
- .github/workflows/smoke.yml
- Earthfile
- package-lock.json
- website/package-lock.json
Refresh `package-lock.json` to fix failing PRs.
> 👷  fix build-docusaurus stage in ci

- .github/workflows/test.yml
Refactor gha for tests and coverage
> :construction_worker:  refactor gha for tests and coverage

- .github/workflows/test.yml
- sonar-project.properties
> :construction_worker:  remove coveralls

- README.md
- packages/core/README.md
- packages/diff/README.md
- packages/docusaurus/README.md
- packages/graphql/README.md
- packages/graphql/docs/index.md
- packages/helpers/README.md
- packages/helpers/docs/index.md
- packages/logger/README.md
- packages/logger/docs/logger.md
- packages/printer-legacy/README.md
- packages/types/README.md
- packages/utils/README.md
- packages/utils/docs/index.md
> 📝 update badges in README.md files

- .github/workflows/publish-docs.yaml
Fix change of domain that replace the repo name :see_no_evil:
> :bug: fix regression on domain change

- docs/try-it.md
- packages/docusaurus/tests/__data__/schema_with_grouping.graphql
> :memo: minor doc udpates

- .github/workflows/test.yml
Checkout `main` branch before running SonarCube coverage.
> :man_mechanic: add main checkout for sonar coverage

- website/package-lock.json
- website/package.json
Upgrade website to `docusaurus` version 3.4
> :package:  upgrade website to docusaurus 3.4

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
Update devcontainer to use earthly container.
> :wrench:  update devcontainer to use earthly container

- scripts/docs-api.sh
Remove some checks and logs to speed the typedoc generation.
> :memo:  update typedoc config

- package-lock.json
- packages/core/package.json
- packages/docusaurus/package.json
- packages/printer-legacy/package.json
Release 1.24.4 fixing relative path support #1427.
> :bookmark:  release 1.24.4

- packages/printer-legacy/tests/unit/relation.test.ts
Fix flaky test with seed `-692630696` related to a mock override.
> :test_tube:  fix flaky test with seed -692630696

- package-lock.json
- packages/core/package.json
- packages/diff/package.json
- packages/docusaurus/package.json
- packages/printer-legacy/package.json
Release 1.25.0 removes `sidebar` file generation.
> :bookmark:  release 1.25.0

- docs/settings.md
- packages/core/src/config.ts
- packages/core/src/generator.ts
- packages/core/src/renderer.ts
- packages/core/tests/unit/generator.test.ts
- packages/core/tests/unit/renderer.test.ts
- packages/printer-legacy/src/const/options.ts
- packages/printer-legacy/src/link.ts
- packages/printer-legacy/tests/unit/__snapshots__/link.test.ts.snap
- packages/printer-legacy/tests/unit/link.test.ts
- packages/types/src/core.d.ts
- packages/types/src/printer.d.ts
> ✨ add support for custom useApiGroup groups name

- docs/settings.md
- website/src/css/custom.css
> 🗒️ minor website fixes

- package-lock.json
- packages/docusaurus/package.json
- website/package-lock.json
- website/package.json
> :package:  update docusaurus 3.5.0

- package-lock.json
- packages/core/docs/config.md
- packages/core/docs/generator.md
- packages/core/docs/renderer.md
- packages/core/package.json
- packages/diff/package.json
- packages/docusaurus/package.json
- packages/graphql/docs/directive.md
- packages/graphql/docs/guard.md
- packages/graphql/docs/introspection.md
- packages/graphql/docs/loader.md
- packages/graphql/package.json
- packages/graphql/src/introspection.ts
- packages/helpers/docs/utils/interpolate.md
- packages/helpers/package.json
- packages/logger/package.json
- packages/printer-legacy/docs/common.md
- packages/printer-legacy/docs/const/options.md
- packages/printer-legacy/docs/example.md
- packages/printer-legacy/docs/link.md
- packages/printer-legacy/package.json
- packages/printer-legacy/src/example.ts
- packages/types/package.json
- packages/types/src/index.d.ts
- packages/utils/docs/fs.md
- packages/utils/docs/object.md
- packages/utils/package.json
> :bookmark:  release 1.26.0

- packages/graphql/src/directive.ts
- packages/graphql/src/guard.ts
- packages/graphql/tests/unit/directive.test.ts
- packages/printer-legacy/src/code.ts
- packages/printer-legacy/src/common.ts
- packages/printer-legacy/src/example.ts
- packages/printer-legacy/src/graphql/enum.ts
- packages/printer-legacy/src/link.ts
- packages/printer-legacy/src/printer.ts
- packages/printer-legacy/src/section.ts
- packages/printer-legacy/tests/unit/common.test.ts
- packages/printer-legacy/tests/unit/example.test.ts
- packages/printer-legacy/tests/unit/link.test.ts
- packages/printer-legacy/tests/unit/printer.test.ts
- packages/types/src/core.d.ts
- packages/types/src/graphql.d.ts
- packages/types/src/helpers.d.ts
- packages/types/src/index.d.ts
- packages/types/src/printer.d.ts
- packages/types/src/utils.d.ts
Remove circular dependencies reported by `npx madge --circular --extensions ts ./packages`
> ♻️ remove circular dependencies

- .github/workflows/test.yml
Fix test workflow issue with deprecated sonar action.
> 👨‍💻 Update sonar action in test.yml

- website/src/pages/showcase.mdx
I wanted to fix typo in Saleor name 😄
> Fix showcase Saleor typo

- .knip.json
- .vscode/settings.json
- packages/cli/tsdoc.json
- packages/core/src/config.ts
- packages/core/tsdoc.json
- packages/diff/tsdoc.json
- packages/docusaurus/tsdoc.json
- packages/graphql/tsdoc.json
- packages/helpers/tsdoc.json
- packages/logger/src/index.ts
- packages/logger/tsdoc.json
- packages/printer-legacy/tsdoc.json
- packages/utils/src/string.ts
- packages/utils/tsdoc.json
- scripts/docs-api.sh
- tsdoc.json
- typedoc.base.json
- typedoc.json
fix packages api docs generation
> :construction_worker:  fix packages api docs generation

- scripts/docs-api.sh
- website/babel.config.js
- website/docusaurus.config.js
- website/package-lock.json
- website/package.json
Upgrade the website to Docusaurus 3.7 with [Faster features](https://github.com/facebook/docusaurus/issues/10556)
> :memo:  upgrade to docusaurus 3.7 with faster feature

- Earthfile
- typedoc.base.json
> :wrench:  fix api doc generation issue

- package-lock.json
- packages/cli/package.json
- packages/core/package.json
- packages/diff/package.json
- packages/docusaurus/package.json
- packages/graphql/package.json
- packages/helpers/package.json
- packages/printer-legacy/package.json
- packages/types/package.json
- packages/utils/package.json
> :bookmark:  release 1.29.0

- Earthfile
> :wrench:  improve earthly performance

- CONTRIBUTING.md
- README.md
- docs/troubleshooting.md
- packages/cli/README.md
- packages/core/src/config.ts
- packages/core/src/generator.ts
- packages/printer-legacy/src/badge.ts
- packages/printer-legacy/src/code.ts
- packages/printer-legacy/src/common.ts
- packages/printer-legacy/src/directive.ts
- packages/printer-legacy/src/example.ts
- packages/printer-legacy/src/frontmatter.ts
- packages/printer-legacy/src/graphql/directive.ts
- packages/printer-legacy/src/graphql/enum.ts
- packages/printer-legacy/src/graphql/interface.ts
- packages/printer-legacy/src/graphql/object.ts
- packages/printer-legacy/src/graphql/operation.ts
- packages/printer-legacy/src/graphql/scalar.ts
- packages/printer-legacy/src/graphql/union.ts
- packages/printer-legacy/src/group.ts
- packages/printer-legacy/src/link.ts
- packages/printer-legacy/src/printer.ts
- packages/printer-legacy/src/relation.ts
- packages/printer-legacy/src/section.ts
- packages/types/src/core.d.ts
- typedoc.json
> :memo:  more doc update

- config/stryker.conf.js
- package-lock.json
- package.json
- packages/core/package.json
- packages/core/src/graphql-config.ts
- packages/core/src/renderer.ts
- packages/core/tests/unit/config.test.ts
- packages/core/tests/unit/diff.test.ts
- packages/core/tests/unit/generator.test.ts
- packages/core/tests/unit/graphql-config.test.ts
- packages/core/tests/unit/printer.test.ts
- packages/core/tests/unit/renderer.test.ts
- packages/types/src/core.d.ts
- scripts/test-suggestions.ts
Mix Stryker results and AI assistant for increasing test quality
> 🧪 improve tests for core

- docs/configuration.md
> :memo:  fix pretty param in config docs

- docs/configuration.md
> :wrench:  fix incorrect use of customDirective in example

- .github/workflows/linter.yml
- package-lock.json
- packages/cli/package.json
- packages/core/package.json
- packages/diff/package.json
- packages/docusaurus/package.json
- packages/graphql/package.json
- packages/helpers/package.json
- packages/printer-legacy/package.json
- packages/utils/package.json
Release fix for #2213.
---
🐛 This release add better support of special characters (e.g. `_`) in entity names, fixing issues like https://github.com/graphql-markdown/graphql-markdown/issues/2213
📄  The documentation has also got its share of fixes.
> 🔖 release 1.29.1

- package-lock.json
- packages/cli/package.json
- packages/core/package.json
- packages/docusaurus/package.json
Fix issues when merging graphql-config with inline config (#2362).
> :bookmark:  release 1.30.3
