graphql-markdown/graphql-markdown

src/lib/renderer.js
This resolves an issue with the file `scalars/float-8.md` that leads to
```
% npx docusaurus graphql-to-doc
(node:21800) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'groups' of null
at Renderer.renderTypeEntities (/doc/node_modules/@edno/docusaurus2-graphql-doc-generator/src/lib/renderer.js:56:41)
at /doc/node_modules/@edno/docusaurus2-graphql-doc-generator/src/lib/renderer.js:38:68
at Array.map (<anonymous>)
at Renderer.renderRootTypes (/doc/node_modules/@edno/docusaurus2-graphql-doc-generator/src/lib/renderer.js:38:49)
at /doc/node_modules/@edno/docusaurus2-graphql-doc-generator/src/lib/generator.js:28:68
at Array.map (<anonymous>)
at /doc/node_modules/@edno/docusaurus2-graphql-doc-generator/src/lib/generator.js:28:48
(node:21800) UnhandledPromiseRejectionWarning: …
```
=> Change RegEx to allow numbers as part of the path

README.md
Changes the capitalization of homePage to homepage to match options.
=> Fix homePage typo in plugin options example

src/lib/printer.js
When using Docusaurus 2.0.0, a compilation error occurs after generating docs for a scalar with a `@specifiedBy` directive, because a newline is missing between `specifiedByLinkCss` and the "Specification" header.
This PR simply adds the missing newline.
(I omitted to make an issue, since the fix is so simple. Hope it is okay 😄)
Error message produced:
```
SyntaxError: [..]docs/graphql/scalars/json.mdx: Unexpected token (2:0)
1 | export const specifiedByLinkCss = { fontSize:'1.5em', paddingLeft:'4px' };
> 2 | ### Specification<a className="link" style={specifiedByLinkCss} target="_blank" href="http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf" title="Specified by http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf">⎘</a>
```
The graphql schema …
=> Fix compilation error for @specifiedBy directives by adding a newline

src/lib/printer.js, tests/integration/lib/__expect__/unix/generator.spec.js/generateDocFromSchemaOutputFolder.hash, tests/unit/lib/__expect__/unix/printer.test.js/printCodeTypeWithInput.md, tests/unit/lib/printer.test.js
For any generated documentation for input types, the keyword that is displayed is `type` instead of `input`. An example of this issue can be found in https://codesandbox.io/s/edno-graphql-markdown-demo-iiyj3c?file=/graphql-markdown.config.js mentioned in the README. When you view the docs for the input types, there is a `type` keyword instead of an `input` keyword.
-  [x] My changes follow the [contributing guidelines](https://github.com/graphql-markdown/graphql-markdown/blob/main/CONTRIBUTING.md) of this project.
=> :bug:  update so the keyword input displays

src/config.js
=> :recycle: code refactoring

src/lib/printer.js, tests/integration/lib/__expect__/unix/generator.spec.js/generateDocFromSchemaOutputFolder.hash, tests/integration/lib/__expect__/unix/generator.spec.js/generateDocFromSchemaWithGroupingOutputFolder, tests/unit/lib/__expect__/unix/printer.test.js/printCodeWithDirective.md, tests/unit/lib/__expect__/unix/printer.test.js/printCodeWithEnum.md, tests/unit/lib/__expect__/unix/printer.test.js/printCodeWithInput.md, tests/unit/lib/__expect__/unix/printer.test.js/printCodeWithInterface.md, tests/unit/lib/__expect__/unix/printer.test.js/printCodeWithObject.md, tests/unit/lib/__expect__/unix/printer.test.js/printCodeWithQuery.md, tests/unit/lib/__expect__/unix/printer.test.js/printCodeWithScalar.md, tests/unit/lib/__expect__/unix/printer.test.js/printCodeWithUnion.md, tests/unit/lib/__expect__/unix/printer.test.js/printCodeWithUnsupported.md, tests/unit/lib/__expect__/unix/printer.test.js/printTypeWithScalarWithSpecifiedBy.md
Remove extra line that appears at the end of some code blocks
Before:
After:
=> :bug:  remove blank line from code block

src/lib/graphql.js, src/lib/printer.js, tests/__data__/schema_with_grouping.graphql, tests/integration/lib/__expect__/unix/generator.spec.js/generateDocFromSchemaOutputFolder.hash, tests/integration/lib/__expect__/unix/generator.spec.js/generateDocFromSchemaWithGroupingOutputFolder, tests/unit/lib/__expect__/unix/printer.test.js/printCodeArguments.md, tests/unit/lib/graphql.test.js, tests/unit/lib/printer.test.js
Closes #535. 
The issue was an incorrect evaluation of `0` when checking if a default value exists.
In addition, the new tests spotted an issue with the mocking used for the printer unit tests.
Integration schema (used also for demo) has also been updated to include this use case.
=> 🐛 fix default value 0 not rendered in doc

src/lib/printer.js, tests/unit/lib/__expect__/unix/printer.test.js/printSectionItemWithSubTypeNonNullableList.md, tests/unit/lib/__expect__/unix/printer.test.js/printSectionItemWithSubTypeNullableList.md, tests/unit/lib/printer.test.js
Similar to #536. This PR fixes missing `[]` when entity type is of list.
=> :bug:  fix missing [] for list entity type

src/lib/printer.js, tests/integration/lib/__expect__/unix/generator.spec.js/generateDocFromSchemaWithGroupingOutputFolder, tests/unit/lib/__expect__/unix/printer.test.js/printSectionItemListNonEmpty.md, tests/unit/lib/__expect__/unix/printer.test.js/printSectionItemWithSubTypeNonNullableList.md, tests/unit/lib/__expect__/unix/printer.test.js/printSectionItemWithSubTypeNullableList.md, tests/unit/lib/printer.test.js
Fix the issues when argument type of array link is not correctly rendered:
- incorrect link: `#` instead of page location
- incorrect array nullability for `[type!]` and `[type]!`
=> :bug:  fix incorrect link format for arg array ypes

tests/__data__/anilist.md, tests/__data__/docusaurus2-graphql-doc-generator.config.js
Fix issue where smoke tests failed when using UrlLoader, if the GraphQL server only supports POST.
=> :test_tube:  fix smoke test Url loader config

.github/workflows/mutation.yml, stryker.conf.js
Remove integration tests from mutation tests to improve performance. 
Mutation tests should only focus on unit tests.
=> :wrench:  update stryker execution options

src/lib/printer.js, tests/integration/lib/__expect__/unix/generator.spec.js/generateDocFromSchemaWithGroupingOutputFolder
Add doc group name to type badges.
=> :sparkles:  add doc group to type badges

package.json
I think the `prepare` script is husky's recommended usage and it makes installing this package via github (pointing at a branch or commit) actually possible (because the `postinstall` hook always fails without husky installed in the repo I'm trying to test changes in).
=> use prepare script for husky install

package.json, yarn.lock
Prepare release 1.13.0
---
🪄 A new option for the schema loader allows custom root types in your schema, see [documentation](https://graphql-markdown.github.io/#custom-root-types), based on a request from @JaKXz.
* use prepare script for husky install by @JaKXz in https://github.com/graphql-markdown/graphql-markdown/pull/623
* 🐛 fix issue when operation names are used as custom type name by @edno & @JaKXz in https://github.com/graphql-markdown/graphql-markdown/pull/622
* @JaKXz made their first contribution in https://github.com/graphql-markdown/graphql-markdown/pull/623
---
=> Release 1.13.0

package-lock.json, packages/diff/package.json, packages/docusaurus/package.json
Release all packages:
- docusaurus `1.15.0`
- core `1.0.0`
- diff `1.0.0`
- utils `1.0.0`
- printer-legacy `1.0.0`
=> :bookmark: prepare to release packages

Earthfile, docs/advanced/schema-loading.md, docs/configuration.md, docs/get-started.md, docs/settings.md, package-lock.json, packages/core/package.json, packages/core/src/config.js, packages/core/src/lib/generator.js, packages/core/src/lib/group-info.js, packages/core/tests/integration/lib/generator.spec.js, packages/diff/package.json, packages/docusaurus/package.json, packages/docusaurus/tests/__data__/docusaurus2-graphql-doc-generator-groups.config.js, packages/docusaurus/tests/__data__/docusaurus2-graphql-doc-generator.config.js, packages/printer-legacy/package.json, packages/printer-legacy/src/index.js, packages/utils/package.json, packages/utils/src/helpers/prettier.js, packages/utils/src/lib/graphql.js
Breaking change is required to fix the issue linked to `@graphql-tools/graphql-file-loader`.
The package is no more provided as a dependency, but must be installed separately.
=> :bug:  remove @graphql-tools/graphql-file-loader as default loader

package-lock.json, package.json, packages/utils/src/graphql.js, packages/utils/tests/__data__/introspection.json, packages/utils/tests/unit/__snapshots__/graphql.test.js.snap, packages/utils/tests/unit/graphql.test.js
Null root types would result in the error "cannot read properties of null" however JSON introspection files could quite reasonably produce a schema will null root types. This fix expands the existing check for undefined types to also skip null types.
Document generation was failing when using JSON introspection files. The tested files are valid and worked with the old @edno/docusaurus2-graphql-doc-generator library but result in the following error when using the JSONFileLoader from @graphql-tools/json-file-loader with a subscriptionType of null. 
```
[ERROR] TypeError: Cannot read properties of null (reading 'name')
```
=> :bug:  Handle null root types

packages/printer-legacy/src/index.js, packages/printer-legacy/tests/unit/__snapshots__/printer.test.js.snap, packages/printer-legacy/tests/unit/printer.test.js
Fix undefined css class for returned types and related types badges.
=> :bug:  fix undefined css class returned types and related types badges

package-lock.json, packages/core/package.json, packages/docusaurus/package.json, packages/printer-legacy/package.json
Release 1.16.5 with fix #772 
---
* :bug:  fix undefined css class returned types and related types badges by @edno in https://github.com/graphql-markdown/graphql-markdown/pull/772
* 📦 update dependency @graphql-markdown/printer-legacy to 1.1.5 by @edno in #773
* 📦 update dependency @graphql-markdown/core to 1.1.5 by @edno in #773
* 📦 update dependency @graphql-markdown/printer-legacy to 1.1.5 by @edno in #773
**Full Changelog**: https://github.com/graphql-markdown/graphql-markdown/compare/1.16.4...1.16.5
---
=> 🔖 release 1.16.5

packages/printer-legacy/src/index.js, packages/printer-legacy/tests/unit/printer.test.js
Add support for `skipDocDirective` on fields (closes #777)
=> :bug: fix skipDocDirective on fields

docs/settings.md, packages/core/src/config.js, packages/core/tests/unit/config.test.js, packages/docusaurus/src/index.js, packages/docusaurus/tests/__data__/groups.md, packages/printer-legacy/tests/unit/printer.test.js, packages/printer-legacy/tests/unit/section.test.js, packages/utils/src/graphql.js, packages/utils/tests/unit/graphql.test.js
Add multiple value supports for `skipDocDirective` option. This a preparatory work for #806
=> ✨ option skipDocDirective supports multiple values

docs/settings.md, packages/core/src/config.js, packages/core/tests/unit/config.test.js, packages/printer-legacy/src/section.js, packages/printer-legacy/tests/unit/section.test.js
Continue implementation of `printTypeOptions.deprecated`. This PR adds the option `skip` that behaves as a shortcut for `--skip "@deprecated"`.
=> :sparkles:  add printTypeOptions deprecated 'skip'

package-lock.json, packages/core/package.json, packages/diff/package.json, packages/docusaurus/package.json, packages/printer-legacy/package.json, packages/utils/package.json
Release 1.17.0
---
Lot of changes in this release 🚀 
* :bug: fix multiline description formatting reported by @patrys in https://github.com/graphql-markdown/graphql-markdown/issues/808
* ✨ update of the option `skipDocDirective` and `--skip` to support multiple values
* 🔮  new option `printTypeOptions.deprecated` gives more control on `deprecated` types from an initial request from @patrys in https://github.com/graphql-markdown/graphql-markdown/issues/735
* ✨ option skipDocDirective supports multiple values by @edno in https://github.com/graphql-markdown/graphql-markdown/pull/810
* ✨ printTypeOptions group deprecated by @edno in https://github.com/graphql-markdown/graphql-markdown/pull/806
* :sparkles:  add printTypeOptions deprecated 'skip' by @edno in …
=> 🔖 release 1.17.0

packages/printer-legacy/src/code.js, packages/printer-legacy/src/const/options.js, packages/printer-legacy/src/graphql/enum.js, packages/printer-legacy/src/graphql/input.js, packages/printer-legacy/src/graphql/object.js, packages/printer-legacy/src/printer.js, packages/printer-legacy/src/section.js, packages/printer-legacy/tests/unit/code.test.js, packages/printer-legacy/tests/unit/graphql/enum.test.js, packages/printer-legacy/tests/unit/graphql/object.test.js, packages/printer-legacy/tests/unit/section.test.js
Improved handling of `@deprecated` directive:
- Print `@deprecated` in code snippet
- Do not print deprecated field and enum (snippet and metadata) if `printDeprecated` is set to `skip`
=> ✨ improve handling of deprecated directive

package-lock.json, packages/core/package.json, packages/docusaurus/package.json, packages/printer-legacy/package.json
---
💅 Fix some inconsistencies in handling `@deprecated` directive:
- `@deprecated` is now printed in code snippets for a better visibility
- `printDeprecated: "skip"` skips all deprecated types, including types in code snippets and metadata (fields, enum values)
* 📦 bump dependency @graphql-markdown/core from 1.2.0 to 1.2.1
* 📦 bump dependency @graphql-markdown/printer-legacy from 1.2.0 to 1.2.1
* 📦 bump peerDependency @graphql-markdown/printer-legacy from 1.2.0 to 1.2.1
* ✨ improve handling of deprecated directive by @edno in https://github.com/graphql-markdown/graphql-markdown/pull/824
---
=> 🔖 release 1.17.1

package-lock.json, packages/core/package.json, packages/diff/package.json, packages/docusaurus/package.json, packages/printer-legacy/package.json, packages/utils/package.json
Publish fix for #815 
---
* 📦 Bump dependency @graphql-markdown/core from 1.2.1 to 1.2.2 by @edno
* 📦 Bump peerDependency @graphql-markdown/printer-legacy from 1.2.1 to 1.2.2 by @edno 
* 📦 Bump dependency @graphql-markdown/utils from 1.2.0 to 1.2.1 by @edno
* 📦 Bump peerDependency @graphql-markdown/printer-legacy from 1.2.1 to 1.2.2 by @edno
* 📦 Bump peerDependency @graphql-markdown/diff from 1.0.7 to 1.0.8 by @edno
* 📦 Bump @graphql-markdown/utils from 1.2.0 to 1.2.1 by @edno
* 📦 npm(deps): Bump @graphql-inspector/core from 4.0.2 to 4.0.3 by @dependabot in https://github.com/graphql-markdown/graphql-markdown/pull/826
* 📦 npm(deps): Bump @graphql-tools/load from 7.8.13 to 7.8.14 by @dependabot in https://github.com/graphql-markdown/graphql-markdown/pull/827
* 📦 Bump dependency …
=> 🔖 release 1.17.2

docs/advanced/custom-directive.md, docs/advanced/custom-root-types.md, docs/advanced/schema-loading.md, package-lock.json, packages/core/package.json, packages/diff/package.json, packages/docusaurus/package.json, packages/docusaurus/tests/__data__/schema_with_grouping.graphql, packages/printer-legacy/package.json, packages/utils/package.json
Release #844 
---
:star_struck: A new really cool feature by @ljiang-ti, [**`customDirective`**](https://graphql-markdown.github.io/docs/settings#customdirective) provides documentation of schema directives at type level. One can now choose to print a custom description for schema directive applying to a type or field. :sparkles: 
```js {6-19}
plugins: [
[
"@graphql-markdown/docusaurus",
{
// ... other options
customDirective: {
auth: {
descriptor: (directive, type) =>
directiveDescriptor(
directive,
type,
"This requires the current user to be in `${requires}` role.",
),
},
// ... other custom directive options
},
},
],
],
```
If you want to see it live, the [`group-by` example documentation](https://graphql-markdown.github.io/examples/group-by) has been update to make use of this …
=> :bookmark:  release 1.18.0

packages/docusaurus/tests/__data__/schema_with_grouping.graphql, packages/printer-legacy/src/code.js, packages/printer-legacy/src/const/strings.js, packages/printer-legacy/src/graphql/object.js, packages/printer-legacy/tests/unit/graphql/interface.test.js, packages/printer-legacy/tests/unit/graphql/object.test.js, packages/printer-legacy/tests/unit/graphql/operation.test.js
Use new argument to print code fields and arguments with indentation (white spaces). This would cover some edge cases described in #850 .
=> Fix indentation level in code section

package-lock.json, packages/core/package.json, packages/docusaurus/package.json, packages/printer-legacy/package.json
Release fix #851 and closes #850. 
---
:bug: Fix the code indentation for fields being incorrect in some cases (#850) by @ljiang-ti in #851.
* :package: bump dependency @graphql-markdown/core from 1.4.0 to 1.4.1
* :package: bump dependency @graphql-markdown/printer-legacy from 1.3.0 to 1.3.1
* :package: bump peerDependency @graphql-markdown/printer-legacy from 1.3.0 to 1.3.1
* :bug: Fix indentation level in code section by @ljiang-ti in https://github.com/graphql-markdown/graphql-markdown/pull/851
---
=> :bookmark: release 1.18.1

docs/settings.md, packages/core/src/config.js
Quick doc refresh for settings to ensure that default values match code, and clean up of the `settings.js` in core package.
=> :recycle:  code clean up and doc refresh

packages/printer-legacy/src/badge.js
Remove circular declaration of `getCustomTags`
```
(node:24) Warning: Accessing non-existent property 'getCustomTags' of module exports inside circular dependency
+build-examples | (Use `node --trace-warnings ...` to show where the warning was created)
```
=> :bug: remove circular declaration of getCustomTags

package-lock.json, packages/core/package.json, packages/diff/package.json, packages/docusaurus/package.json, packages/printer-legacy/package.json, packages/utils/package.json
> :warning: *This release introduces minor breaking changes, see section breaking changes.*
---
:label: Building upon `customDirective` released in 1.18.0, we added to it a new option `tag` that allows one to display custom badges (tags) in the documentation pages. 
The feature is an extension of the `customDirective` by using the already available directive processing. It works the same way as `descriptor`, and also come with an helper `directiveTag`... more details in the [documentation](https://graphql-markdown.github.io/docs/advanced/custom-directive).
```js
customDirective: {
beta: {
tag: (directive) => ({
text: directive?.name.toUpperCase(),
classname: "badge--danger",
}),
},
```
* Since tags have now a dedicated handler, the directive declared in `customDirective` for `descriptor` …
=> :bookmark:  release 1.19.0

.vscode/settings.json, Earthfile, docs/configuration.md, docs/intro.md, package-lock.json, packages/core/package.json, packages/core/src/config.js, packages/core/src/graphql-config.js, packages/core/tests/unit/config.test.js, packages/core/tests/unit/graphql-config.test.js, packages/docusaurus/scripts/config-plugin.js, packages/docusaurus/tests/__data__/.graphqlrc, packages/docusaurus/tests/__data__/anilist.md, packages/docusaurus/tests/__data__/docusaurus2-graphql-doc-generator-multi-instance.config.js, packages/docusaurus/tests/__data__/docusaurus2-graphql-doc-generator-tweets.graphqlrc.js, packages/docusaurus/tests/__data__/groups.md, packages/docusaurus/tests/e2e/specs/cli.spec.js
A `graphql-config` support with limitations:
- loaders are managed by `@graphql-markdown/utils/graphql`
- projects are not supported
- `include`, `exclude` and glob pattern are not supported
- schema options (eg headers) are not supported
Example `.graphqlrc` (root folder):
```yaml
schema: "https://graphql.anilist.co/"
extensions:
graphql-markdown:
linkRoot: "/examples/default"
baseURL: "."
homepage: "data/anilist.md"
loaders:
UrlLoader:
module: "@graphql-tools/url-loader"
options: 
method: "POST"
printTypeOptions:
deprecated: "group"
docOptions:
pagination: false,
toc: false
```
:warning: **Note that `schema` is not part of the extension configuration, but part of the default `graphql-config` configuration.**
=> :sparkles:  add support for graphql-config (#828)

docs/advanced/additional-schema.md, docs/configuration.md, packages/core/src/config.js, packages/core/src/graphql-config.js, packages/core/tests/unit/graphql-config.test.js, packages/docusaurus/src/index.js, packages/docusaurus/tests/__data__/.graphqlrc
This enable projects support for GraphQL config, removing the limitation on multi schema (see documentation).
=> :sparkles:  add graphql-config projects support

docs/configuration.md, packages/core/src/graphql-config.js, packages/core/tests/unit/graphql-config.test.js
Add support of schema options when defined at `schema` level in GraphQL Config. 
The options are pushed to each loaders.
=> :sparkles:  support schema options in graphql-config

package-lock.json, packages/core/package.json, packages/diff/package.json, packages/docusaurus/package.json
:sparkles: [GraphQL Config](https://the-guild.dev/graphql/config) is now supported, see the [documentation](https://graphql-markdown.github.io/docs/configuration#graphql-config) for more information and limitations :rocket: 
First install the package `graphql-config`, then you are ready to go.
```bash
npm install graphql-config
```
Example `.graphqlrc`:
```yaml
schema: "https://graphql.anilist.co/"
extensions:
graphql-markdown:
linkRoot: "/examples/default"
baseURL: "."
homepage: "data/anilist.md"
loaders:
UrlLoader:
module: "@graphql-tools/url-loader"
options: 
method: "POST"
printTypeOptions:
deprecated: "group"
docOptions:
pagination: false,
toc: false
```
* :technologist:  force loading  @docusaurus/logger on module init by @edno in …
=> :bookmark:  release 1.20.0

package-lock.json, package.json, packages/core/package.json, packages/diff/package.json, packages/docusaurus/package.json, packages/printer-legacy/package.json, packages/utils/package.json
:package: Update compatibility with `prettier` 3.0.0 when using [`pretty`](https://graphql-markdown.github.io/docs/settings#pretty) setting. :magic_wand: 
* :package: bump dependency @graphql-markdown/core to 1.6.1
* :package: bump dependency @graphql-markdown/printer-legacy to 1.4.1
* :package: chore(deps): update dependency prettier to v3 by @renovate in https://github.com/graphql-markdown/graphql-markdown/pull/892
* :package: bump dependency @graphql-markdown/utils to 1.5.1
* :package: bump peerDependency @graphql-markdown/diff to 1.0.14
* :package: bump peerDependency @graphql-markdown/printer-legacy to 1.4.1
* :package: chore(deps): update dependency prettier to v3 by @renovate in https://github.com/graphql-markdown/graphql-markdown/pull/892
* :package: bump dependency …
=> :bookmark:  release 1.20.1

docs/settings.md, packages/core/src/config.js, packages/core/tests/unit/config.test.js, packages/docusaurus/src/index.js, packages/printer-legacy/src/const/options.js, packages/printer-legacy/src/printer.js, packages/printer-legacy/tests/unit/printer.test.js
Implements #895 by adding a new option `printTypeOptions.codeSection` and CLI flag `--noCode`.
=> 895 add print option to hide code blocks

package-lock.json, packages/core/package.json, packages/docusaurus/package.json, packages/printer-legacy/package.json
:mage: New option `printTypeOptions.codeSection` and CLI flag `--noCode` for disabling the codeblock section, based on an initial request from @ris314 in https://github.com/graphql-markdown/graphql-markdown/issues/895, see [documentation](https://graphql-markdown.github.io/docs/settings#printtypeoptions) for more information.
* :sparkles:  add print option to hide code blocks by @edno in https://github.com/graphql-markdown/graphql-markdown/pull/897
* :package: bump dependency @graphql-markdown/core to 1.6.2
* :package: bump dependency @graphql-markdown/printer-legacy to 1.4.2
* :sparkles:  add print option to hide code blocks by @edno in https://github.com/graphql-markdown/graphql-markdown/pull/897
* :package: bump peerDependency @graphql-markdown/printer-legacy to 1.4.2
* :sparkles:  add …
=> :bookmark: release 1.20.2

.vscode/settings.json, packages/printer-legacy/src/badge.js, packages/printer-legacy/src/link.js, packages/printer-legacy/src/relation.js, packages/printer-legacy/tests/unit/link.test.js, packages/printer-legacy/tests/unit/relation.test.js
Fix issue where "relation of" sections do not have correct CSS classname.
This was a regression after refactoring badge handling.
**Bug**
**Fix**
=> :bug: fix badge css for relation of type sections

package-lock.json, packages/core/package.json, packages/docusaurus/package.json, packages/printer-legacy/package.json
:bug: Fix the CSS issue for type badges in *related type* sections (see option [`printTypeOptions.relatedTypeSection`](https://graphql-markdown.github.io/docs/settings#printtypeoptions)).
* **Before fix**
* **After fix**
* :package: bump dependency @graphql-markdown/core to 1.6.3
* :package: bump dependency @graphql-markdown/printer-legacy to 1.4.3
* :package: bump peerDependency @graphql-markdown/printer-legacy to 1.4.3
* :bug: fix badge css for relation of type sections by @edno in https://github.com/graphql-markdown/graphql-markdown/pull/908
=> :bookmark:  release 1.20.3

packages/core/src/generator.js
Fix typo introduced in https://github.com/graphql-markdown/graphql-markdown/blame/ba1002f82f1072fe4afe4c4decf39e8e2dfef99d/packages/core/src/generator.js#L47
However, this typo does not seem to impact the behavior :man_shrugging:
=> :bug: fix generateDocFromSchema generator.js

config/.eslintrc.js, packages/core/src/graphql-config.ts, packages/core/tests/unit/config.test.ts, packages/docusaurus/src/index.ts, packages/printer-legacy/src/code.ts, packages/printer-legacy/src/graphql/directive.ts, packages/printer-legacy/src/graphql/enum.ts, packages/printer-legacy/src/graphql/object.ts, packages/printer-legacy/src/link.ts, packages/printer-legacy/src/section.ts, packages/printer-legacy/tests/unit/common.test.ts, packages/printer-legacy/tests/unit/graphql/object.test.ts, packages/utils/src/logger.ts, packages/utils/tests/__data__/dummy_logger.js, packages/utils/tests/unit/directive.test.ts, packages/utils/tests/unit/graphql.test.ts
Enable TS eslint rule `eslint explicit-function-return-type`
=> :wrench:  add eslint explicit-function-return-type

package-lock.json, packages/core/package.json, packages/diff/package.json, packages/docusaurus/package.json, packages/graphql/package.json, packages/helpers/package.json, packages/logger/package.json, packages/printer-legacy/package.json, packages/types/package.json, packages/utils/package.json
This is a pre-release migrating the code base from JS to TS.
- Custom directive helpers have been moved to dedicated packages, see docs.
- Helper `directiveDescriptor` now supports `description` placeholder, where `description` is the default directive description.
- Typing is available in a dedicated package `@graphql-markdown/types`.
- Modules `helpers`, `graphql` and `logger` have been extracted from `@graphql-markdown/utils` into their own package.
- `Logger` has now a single method called `Logger()`.
- TS API is getting documented, see `API` in our docs.
- More and better tests.
=> :bookmark:  pre-release 1.21.0-next.0

Earthfile, docs/configuration.md, docs/settings.md, packages/docusaurus/src/index.ts, packages/docusaurus/tests/__data__/docusaurus2-graphql-doc-nobuild.js, packages/docusaurus/tests/e2e/specs/cli.spec.js
New flag `runOnBuild` that allows disabling the new behaviour of generating docs on Docusaurus build.
Default value is `true`.
NOTE: this flag is only part of `@graphql-markdown/docusaurus`, ie not available for `core`.
=> :sparkles:  add flag runOnBuild

typedoc.json
Remove the deprecated option `anchorFormat` breaking API doc generation with Typedoc Markdown
=> :construction_worker:  remove deprecated option for typedoc-markdown breaking doc ci

packages/docusaurus/src/index.ts
Ensure that `runOnBuild` is disabled by default, see bug #991
=> :technologist:  disable runOnBuild by default (bug #991)

packages/docusaurus/tests/__data__/docusaurus2-graphql-doc-build.js, packages/docusaurus/tests/e2e/specs/cli.spec.js
Fix smoke tests for `runOnBuild` broken by  commit 66d956b
=> :test_tube:  fix smoke tests for runOnBuild

docs/settings.md, package-lock.json, packages/core/package.json, packages/diff/package.json, packages/docusaurus/package.json, packages/graphql/package.json, packages/helpers/package.json, packages/logger/package.json, packages/printer-legacy/package.json, packages/types/package.json, packages/utils/package.json
🚀  **BIG release** 🚀 
This is an exceptionally big and packed release with a lot of changes, so read carefully the release notes before upgrading.
The main changes are under the hood as we migrated the codebase from Javascript to Typescript to simplify the coding experience but also to increase the code safety.
- `onlyDocDirective` filters the schema entities to be rendered in the documentation. This is the counterpart of `skipDocDirective`, based on a request from XXXX. See documentation.
- `metatags` adds HTML metadata to pages using [Docusaurus head metadata](https://docusaurus.io/docs/markdown-features/head-metadata), based on a request from XXXX. See documentation.
- Helper `directiveDescriptor` now supports the `description` placeholder, where `description` is the default …
=> 🔖 release 1.21.0

config/stryker.conf.js, packages/utils/src/prettier.ts
Use Stryker [`disable comment`](https://stryker-mutator.io/docs/stryker-js/disable-mutants/#using-a--stryker-disable-comment) instead of config pattern for excluding code from mutation.
This will prevent noisy warning that `prettier.ts` is not found in packages other than `utils`.
=> :test_tube:  chore(tests): use stryker disable comment

docs/advanced/custom-directive.md, docs/advanced/homepage.md, docs/configuration.md, docs/get-started.md, docs/settings.md
Update admonition used in docs with Docusaurus syntax:
- https://docusaurus.io/docs/migration/v3#admonition-warning
- https://docusaurus.io/docs/markdown-features/admonitions
=> :memo:  (doc) update docusaurus admonition for v3 compatibility

package-lock.json, packages/core/package.json, packages/docusaurus/package.json, packages/printer-legacy/package.json
Release implementation of #1096
---
:magic_wand:   Improve compatibility with Docusaurus 3 to use new [admonition format](https://docusaurus.io/docs/markdown-features/admonitions) for the `deprecated` admonition (see #1096).
| Docusaurus 2 | Docusaurus 3 |
|---|---|
|<code>:::caution DEPRECATED</code>|<code>:::warning[DEPRECATED]</code>|
* :package: bump dependency @graphql-markdown/core to 1.7.2 #1103 
* :package: bump dependency @graphql-markdown/printer-legacy to 1.5.2 #1103 
* :package: bump peer dependency @graphql-markdown/printer-legacy to 1.5.2 #1103 
* :sparkles:  (feat) replace caution admonition by warning for docusaurus v3 by @edno in https://github.com/graphql-markdown/graphql-markdown/pull/1101
---
=> :bookmark:  release 1.21.2

packages/printer-legacy/src/const/strings.ts, packages/printer-legacy/src/frontmatter.ts, packages/printer-legacy/src/printer.ts, packages/printer-legacy/tests/unit/frontmatter.test.ts, packages/printer-legacy/tests/unit/printer.test.ts
Add list and object support for `frontMatter` option needed for #1168.
=> :sparkles:  add list and object support for frontMatter option

website/src/pages/index.js
Add missing `alt` prop for website main page images reported by SonarCloud.
=> :memo:  add missing alt prop for website main page images

.github/workflows/test.yml
Fix GHA warning when running coveralls action
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: coverallsapp/github-action@master. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
=> Update covervallsapp action version

package-lock.json, packages/core/package.json, packages/diff/package.json, packages/docusaurus/package.json, packages/graphql/package.json, packages/helpers/package.json, packages/logger/package.json, packages/printer-legacy/package.json, packages/types/package.json, packages/utils/package.json
Release 1.23.0
:sparkle: Executable types (operations and related directives) and system types (entity types) have now separate sections. The behaviour can be disabled by setting the option `printTypeOptions.useApiGrou`  to `false` or using the cli flag `--noApiGroup`.
The online examples have been updated with one using the new sections and one with the option disabled. Note that the examples have some custom CSS that is not part of the default package.
=> :label: release 1.23.0

docs/advanced/additional-schema.md, docs/advanced/custom-directive.md, docs/advanced/custom-root-types.md, docs/advanced/docs-multi-instance.md, docs/advanced/examples.md, docs/advanced/group-by-directive.md, docs/advanced/schema-loading.md, docs/configuration.md, docs/settings.md, packages/core/src/config.ts, packages/core/src/generator.ts, packages/core/src/graphql-config.ts, packages/core/tests/integration/generator.spec.ts, packages/core/tests/unit/config.test.ts, packages/core/tests/unit/generator.test.ts, packages/core/tests/unit/graphql-config.test.ts, packages/core/tests/unit/renderer.test.ts, packages/docusaurus/scripts/config-plugin.js, packages/docusaurus/tests/__data__/docusaurus2-graphql-doc-build.js, packages/docusaurus/tests/__data__/docusaurus2-graphql-doc-generator-groups.config.js, packages/docusaurus/tests/__data__/docusaurus2-graphql-doc-generator-tweets.graphqlrc.js, packages/docusaurus/tests/__data__/docusaurus2-graphql-doc-generator.config.js, packages/docusaurus/tests/__data__/docusaurus2-graphql-doc-nobuild.js, packages/docusaurus/tests/__data__/groups.md, packages/graphql/src/directive.ts, packages/printer-legacy/src/const/options.ts, packages/printer-legacy/tests/unit/printer.test.ts, packages/types/src/core.d.ts, packages/types/src/printer.d.ts
Tidy up types as `Maybe` was not clearly declared for `core` types.
=> :recycle:  tidy up types

SECURITY.md
Use github security advisories report instead of email report.
=> :memo: use github security advisories report

package-lock.json, packages/graphql/package.json, packages/helpers/package.json, packages/utils/package.json
Fix issue #1458 by restricting `graphql` package version to 16 and fix peer deps declarations.
=> :package:  restrict graphql version to 16 and fix peer deps declarations

docs/advanced/custom-directive.md, docs/advanced/custom-root-types.md, docs/advanced/docs-multi-instance.md, docs/advanced/schema-loading.md, docs/troubleshooting.md
Clean up docs to fix code lines highlights and bump the troubleshooting graphql resolution.
=> :memo:  clean up docs

scripts/custom-frontmatter.js
Fix `typedoc` custom frontmatter script (upgrade deprecation) reported in https://github.com/graphql-markdown/graphql-markdown/actions/runs/9632755071/job/26566326411
=> :memo:  fix typedoc custom frontmatter script

package-lock.json, packages/core/package.json, packages/diff/package.json, packages/docusaurus/package.json, packages/graphql/package.json, packages/helpers/package.json, packages/printer-legacy/package.json, packages/utils/package.json
Technical release for dependencies upgrade.
⚠️ This version removes compatibility with the `graphql` package version below 16 (see issue #1458).
=> 🔖 release 1.24.2

.github/workflows/publish-docs.yaml
remove setup nodejs from publish docs workflow, no more needed since all the job is perfomed by earthly
=> :construction_worker:  remove setup nodejs from publish docs workflow

package-lock.json, packages/printer-legacy/src/const/strings.ts, packages/printer-legacy/src/link.ts, packages/printer-legacy/tests/unit/__snapshots__/link.test.ts.snap, packages/printer-legacy/tests/unit/graphql/directive.test.ts, packages/printer-legacy/tests/unit/graphql/input.test.ts, packages/printer-legacy/tests/unit/graphql/interface.test.ts, packages/printer-legacy/tests/unit/graphql/object.test.ts, packages/printer-legacy/tests/unit/graphql/operation.test.ts, packages/printer-legacy/tests/unit/graphql/union.test.ts, packages/printer-legacy/tests/unit/link.test.ts, packages/printer-legacy/tests/unit/section.test.ts
Follows Docusaurus best practices by appending `.mdx` to links in order to have 1st class support for relative paths.
This should fix #1427 .
Demo preview: https://codesandbox.io/p/devbox/determined-spence-mrpnmp
=> ✨ support relative paths

package-lock.json, packages/diff/package.json, packages/printer-legacy/package.json
Attempt to fix some CVEs report from Snyk.
CVEs reported by Snyk cannot be exploited.
=> fix snyk reports

package.json, packages/printer-legacy/src/badge.ts, packages/printer-legacy/src/relation.ts, packages/printer-legacy/tests/unit/relation.test.ts
Enforce test robustness by enabling randomisation for Jest in CI.
=> 👷 set jest randomize for ci

docs/settings.md
Add warning about docs structure after upgrade to 1.3.0 in docs
=> 📝 add warning upgrade 1.3.0 in docs

packages/utils/src/fs.ts, packages/utils/tests/__mocks__/node:fs/promises.ts
Replace deprecated `fs.rmdir` by `fs.rm`, see https://nodejs.org/api/deprecations.html#DEP0147
=> :recycle:  replace deprecated fs.rmdir by fs.rm

package-lock.json, packages/core/package.json, packages/docusaurus/package.json, packages/logger/package.json
Fix @graphql-markdown logs not being printed by Docusaurus 3 (#1802).
=> 🔖 Release 1.26.3

packages/core/src/config.ts, packages/core/tests/unit/config.test.ts, packages/core/tests/unit/graphql-config.test.ts
Fix validation error report when `--hierarchy` flag passed in CLI, but failed validation because of conflict with the default config value.
=> :bug:  fix error when hierarchy defined in cli but validation failed

package-lock.json, packages/core/package.json, packages/diff/package.json, packages/docusaurus/package.json, packages/graphql/package.json, packages/helpers/package.json, packages/printer-legacy/package.json, packages/types/package.json, packages/utils/package.json
Release 1.26.4
---
🐛 Bug fixes for [`printTypeOptions`](https://graphql-markdown.dev/docs/settings#printtypeoptions) parameters `hierarchy` and `example`.
* ♻️ remove circular dependencies by @edno in https://github.com/graphql-markdown/graphql-markdown/pull/1820
* :bug:  fix error when hierarchy defined in cli but validation failed by @edno in https://github.com/graphql-markdown/graphql-markdown/pull/1884
* 🐛 fix example option with schema containing recursive types by @edno in https://github.com/graphql-markdown/graphql-markdown/pull/1887 reported in #1883 by XXXX
**Full Changelog**: https://github.com/graphql-markdown/graphql-markdown/compare/1.26.3...1.26.4
=> :bookmark:  release 1.26.4

package-lock.json, packages/core/src/generator.ts, packages/core/tests/unit/generator.test.ts, packages/docusaurus/package.json, packages/docusaurus/src/index.ts, packages/printer-legacy/package.json, packages/printer-legacy/src/common.ts, packages/printer-legacy/src/const/options.ts, packages/printer-legacy/src/printer.ts, packages/printer-legacy/tests/unit/common.test.ts, packages/printer-legacy/tests/unit/printer.test.ts, packages/types/src/core.d.ts, packages/types/src/printer.d.ts
Move `@docusaurus\utils` dependency from `printer-legacy` to `docusaurus` to remove Docusaurus dependencies when using `cli`.
=> :sparkles:  move docusaurus\utils from printer to docusaurus plugin

config/.eslintrc.js, docs/settings.md, packages/core/src/config.ts, packages/core/tests/unit/config.test.ts, packages/docusaurus/src/index.ts, packages/types/src/core.d.ts
Remove support of deprecated settings:
- `docOptions.pagination` | `--noPagination`
- `docOptions.toc` | `--noToc`  
- `printTypeOptions.useApiGroup` | `--noApiGroup`
=> :sparkles:  remove deprecated settings

Earthfile, package-lock.json, packages/cli/package.json, packages/core/package.json, packages/docusaurus/package.json, packages/printer-legacy/package.json, packages/types/package.json
Release 1.27.0
🚀 This release introduces a **new NodeJS command line package** `@graphql-markdown/cli` allowing generating Markdown files without Docusaurus dependencies.
This is still an early release and it is not yet documented, but you can experiment with it and [give your feedback](https://github.com/graphql-markdown/graphql-markdown/issues) on this new package when used with other static site generators - note that you'll need MDX support.
1. Install `npm install @graphql-markdown/cli`
2. Usage `npx gqlmd graphql-to-doc`
ℹ️  The `cli` package works similarly to the Docusaurus plugin, but it relies on a [GraphQL config file](https://the-guild.dev/graphql/config/docs/user/usage) for the settings. You can find examples of settings in the [test folder of the …
=> :bookmark: release 1.27.0

packages/docusaurus/src/mdx/index.ts, packages/docusaurus/tests/unit/mdx/index.test.ts, packages/printer-legacy/src/badge.ts, packages/printer-legacy/src/relation.ts, packages/printer-legacy/tests/unit/badge.test.ts, packages/types/src/printer.d.ts
Remove docusaurus css classname specific constants from default badge handling.
=> :bug:  fix badge classname linked to docusaurus css

.knip.json, packages/core/src/renderer.ts, packages/core/tests/unit/renderer.test.ts, packages/docusaurus/src/mdx/category.ts, packages/docusaurus/src/mdx/index.ts, packages/docusaurus/tests/unit/mdx/index.test.ts, packages/printer-legacy/src/badge.ts, packages/printer-legacy/src/const/strings.ts, packages/printer-legacy/src/mdx/index.ts, packages/printer-legacy/tests/unit/badge.test.ts, packages/types/src/core.d.ts, packages/types/src/printer.d.ts, website/src/css/custom.css
fix missing export for generateIndexMetafile in docusaurus mdx](https://github.com/graphql-markdown/graphql-markdown/commit/27f50856fd9993faf41fbd0f6a4510ad17b61fe8)
=> 🐛 fix docusaurus category file not exposed

Earthfile, packages/docusaurus/tests/__data__/docusaurus2-graphql-doc-build.js, packages/docusaurus/tests/__data__/docusaurus2-graphql-doc-nobuild.js, packages/docusaurus/tests/__data__/e2e-test-webpack-plugin/index.js, packages/docusaurus/tests/__data__/e2e-test-webpack-plugin/package.json
Add custom webpack config/plugin for Docusaurus to silent webpack warnings breaking e2e tests.
=> :construction_worker:  silent e2e tests webpack warnings

.devcontainer/devcontainer.json
remove unused postCreateCommand from devContainer
=> :construction_worker:  remove unused postCreateCommand from devContainer

packages/docusaurus/src/mdx/index.ts, packages/utils/src/string.ts, packages/utils/tests/unit/string.test.ts
Add missing support for escaping special MDX characters when rendering links.
This should fix #2214
=> :bug:  fix mdx compilation error when underscore used with entity name

config/jest.config.js, packages/cli/tsconfig.test.json, packages/core/tsconfig.test.json, packages/diff/tsconfig.test.json, packages/docusaurus/tsconfig.test.json, packages/graphql/tsconfig.test.json, packages/helpers/tsconfig.test.json, packages/logger/tsconfig.test.json, packages/printer-legacy/tsconfig.test.json, packages/utils/tsconfig.test.json
Jest `ts-jest` config `isolatedModules` is deprecated in favor of  `isolatedModules` in tsconfig.
=> :wrench:  update jest config related to deprecation of isolatedModules

docs/settings.md, packages/core/src/config.ts, packages/core/src/renderer.ts, packages/core/tests/unit/config.test.ts, packages/core/tests/unit/renderer.test.ts, packages/types/src/core.d.ts
Add support for disabling homepage generation (#2233 and #2234).
`homepage: false` will now prevent the generation of the homepage.
=> :sparkles:  add support for disabling homepage

packages/utils/src/prettier.ts, packages/utils/tests/unit/prettier.test.ts
User `mdx` parser instead of `markdown` when calling prettier, and add support for local config file.
=> :bug:  fix prettier support for mdx with config

package-lock.json, packages/cli/package.json, packages/core/package.json, packages/diff/package.json, packages/docusaurus/package.json, packages/graphql/package.json, packages/helpers/package.json, packages/logger/package.json, packages/printer-legacy/package.json, packages/types/package.json, packages/utils/package.json
This release improves prettier support config file and now uses `mdx` parser instead of `markdown`. It also comes with a new configuration option for `homepage` that you can now set to `false` to disable its generation.
=> :bookmark:  release 1.30.0

package-lock.json, packages/cli/package.json, packages/core/package.json, packages/docusaurus/package.json
Version bump to release a new package `core` to fix the "magic" warning.
=> 🏷️ release 1.31.1

packages/docusaurus/tests/__data__/schema_with_grouping.graphql, packages/graphql/src/formatter.ts, packages/graphql/tests/unit/formatter.test.ts, packages/printer-legacy/tests/unit/graphql/operation.test.ts
Fix issue with `InputObject` fields with default value
```graphql
type Query {
searchRole(
roles: [Roles!]! = [ADMIN]
sort: EntitySort = { field: SOME_FIELD, direction: ASC }
): Int!
}
```
| Before fix | After fix |
|---|---|
| <img width="1000" height="133" alt="Screenshot 2025-08-27 at 18 59 55" src="https://github.com/user-attachments/assets/3be1d8ed-218c-4065-8ca4-be0dd6c62c1a" /> |  <img width="1014" height="152" alt="Screenshot 2025-08-27 at 18 51 16" src="https://github.com/user-attachments/assets/dd23a82b-7659-4c6e-acab-26bc8d9d836a" /> |
=> :bug: fix issue with default values for object type fields
